Repository rancher/opni, pull requests merged in 2023-04, with the labels that each got.

#1274 chore : update version for 0.9.1-rc2 release candidate
  Tiltfile
  ci.cue
  packages/opni-agent/opni-agent/charts/Chart.yaml
  packages/opni-agent/opni-agent/package.yaml
  packages/opni/opni/charts/Chart.yaml
  packages/opni/opni/package.yaml
  pkg/resources/opniopensearch/resources.go
  plugins/aiops/pkg/gateway/admin_test.go
  plugins/aiops/pkg/gateway/plugin.go
  plugins/logging/pkg/gateway/admin.go
  plugins/logging/pkg/gateway/admin_v2.go
  plugins/logging/pkg/gateway/admin_v2_test.go
  plugins/logging/pkg/gateway/plugin_test.go
Labels: chore

#1283 load compatibility k8s for slo plugin
  plugins/slo/pkg/apis/slo/compat.go
Labels: bug, alerting

#1305 Fix alerting condition evalutation triggers
  plugins/alerting/pkg/alerting/condition_handlers.go
  plugins/alerting/pkg/alerting/drivers/cluster_driver.go
  plugins/alerting/pkg/alerting/impl.go
  plugins/alerting/pkg/alerting/plugin.go
  plugins/alerting/pkg/alerting/sync.go
  plugins/alerting/pkg/alerting/system.go
Labels: bug, alerting

#1026 OEP - implement streaming data-loader for log anomaly detection model training to reduce memory pressure
  enhancements/aiops/20230203-introduce-streaming-dataloader-in-log-anomaly-detection-model-training.md
Labels: OEP

#1320 fix test flake in caching test suite
  pkg/caching/grpc_test.go
Labels: bug, testing

#1176 Collect kubernetes + workload metrics with OTEL
  Tiltfile
  apis/clientgo_scheme.go
  apis/core/v1beta1/collector_meta.go
  apis/core/v1beta1/collector_types.go
  apis/core/v1beta1/zz_generated.deepcopy.go
  apis/monitoring/v1beta1/collector_config_types.go
  apis/monitoring/v1beta1/zz_generated.deepcopy.go
  config/agent-crd/bases/core.opni.io_collectors.yaml
  config/agent-crd/bases/monitoring.opni.io_collectorconfigs.yaml
  config/agent-crd/kustomization.yaml
  config/crd/bases/core.opni.io_collectors.yaml
  config/crd/bases/monitoring.opni.io_collectorconfigs.yaml
  config/crd/kustomization.yaml
  controllers/core_collector_controller.go
  controllers/core_collector_controller_test.go
  go.mod
  go.sum
  images/otel-collector/Dockerfile
  images/otel-collector/components.go
  images/otel-collector/components_test.go
  images/otel-collector/go.mod
  images/otel-collector/go.sum
  images/otel-collector/main.go
  images/otel-collector/main_others.go
  images/otel-collector/main_windows.go
  images/otel-collector/ocb-config.yaml
  internal/cmd/testenv/main.go
  magefile.go
  packages/opni-agent/opni-agent/charts/crds/crds.yaml
  packages/opni-agent/opni-agent/charts/templates/rbac_v2.yaml
  packages/opni/opni/charts/crds/crds.yaml
  pkg/otel/otel_suite_test.go
  pkg/otel/templates.go
  pkg/otel/templates/metrics.tmpl
  pkg/otel/templates_test.go
  pkg/otel/types.go
  pkg/resources/collector/collector.go
  pkg/resources/collector/discovery/discoverer.go
  pkg/resources/collector/discovery/podmonitor.go
  pkg/resources/collector/discovery/servicemonitor.go
  pkg/resources/collector/metrics.go
  pkg/resources/collector/templates.go
  pkg/resources/collector/workloads.go
  pkg/test/environment.go
  pkg/test/test_cluster_driver.go
  pkg/test/testdata/otel/base.tmpl
  plugins/metrics/pkg/agent/drivers/external_operator.go
  plugins/metrics/pkg/agent/drivers/otel/otel_driver.go
  plugins/metrics/pkg/agent/drivers/util/util.go
  plugins/metrics/pkg/agent/plugin.go
  plugins/metrics/pkg/apis/node/extensions.go
  plugins/metrics/pkg/apis/node/node.pb.go
  plugins/metrics/pkg/apis/node/node.proto
  plugins/metrics/pkg/apis/node/validation.go
  plugins/metrics/pkg/backend/metrics.go
  test/resources/monitoringcrds.yaml
  tools.go
Labels: enhancement, monitoring

#1311 OEP: An alternative approach to improve model training on large dataset
  enhancements/aiops/20230414-An-alternative-approach-to-handle-large-training-data-in-log-anomaly-detection-model-training.md
Labels: OEP

#1348 chore : update version for 0.9.2-rc4 release candidate
  Tiltfile
  ci.cue
  packages/opni-agent/opni-agent/charts/Chart.yaml
  packages/opni-agent/opni-agent/package.yaml
  packages/opni/opni/charts/Chart.yaml
  packages/opni/opni/package.yaml
  pkg/resources/opniopensearch/resources.go
  plugins/aiops/pkg/gateway/admin_test.go
  plugins/aiops/pkg/gateway/plugin.go
  plugins/logging/pkg/gateway/admin_v2.go
  plugins/logging/pkg/gateway/drivers/management/kubernetes_manager/kubernetes_manager_test.go
Labels: chore
